- name: Downloading Auth LDAP Library
  get_url:
    url: "{{ guacamole_dl_url }}/binary/{{ guacamole_auth_ldap_package }}"
    dest: "{{ guacamole_src_dir }}"
    checksum: "{{ guacamole_auth_ldap_checksum }}"
  become: true

- name: Extracting Auth LDAP Library
  unarchive:
    src: "{{ guacamole_src_dir }}/{{ guacamole_auth_ldap_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true

- name:  Copying Auth LDAP Connector
  copy:
    src: "{{ guacamole_src_dir }}/guacamole-auth-ldap-{{ guacamole_version }}/guacamole-auth-ldap-{{ guacamole_version }}.jar"
    dest: /etc/guacamole/extensions/
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true

