---
- name: Ensure Guacamole directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
  become: true
  with_items:
    - /etc/guacamole
    - /etc/guacamole/lib
    - /etc/guacamole/extensions

- name: Create guacamole.properties
  template:
    src: guacamole.properties.j2
    dest: /etc/guacamole/guacamole.properties
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd

- name: Run auth tasks
  include_tasks: "auth_{{ guacamole_auth_provider }}.yml"
  loop: "{{ guacamole_auth_providers }}"
  when: guacamole_auth_providers is defined

# Run auth_basic if no other providers are defined.
- name: Run auth tasks
  include_tasks: "auth_basic.yml"
  when: "{{ guacamole_auth_providers | default(true, true) }}"

- name: Creating Tomcat symlink For guacamole.properties
  file:
    src: /etc/guacamole
    dest: "/usr/share/{{ guacamole_tomcat }}/.guacamole"
    state: link
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd
