---
# tasks file for ansible-guacamole
- name: resolve platform specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
        - 'default.yml'
      paths:
        - '{{ role_path }}/vars'

- name: resolve platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths:
        - '{{ role_path }}/tasks'

- include_tasks: install_server.yml
- include_tasks: config.yml
# This should probably be a handler.
- include_tasks: services.yml
- include_tasks: install_client.yml

- name: Remove the build dir if it exists
  file:
    path: "{{ guacamole_src_dir }}"
    state: absent
  when: guacamole_src_dir is defined
