---
- name: redhat | Enabling EPEL Repo
  yum:
    name: ["epel-release"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Enabling RPM Fusion Repos
  yum:
    name: "{{ guacamole_redhat_fusion_repos }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Adding font used by Guacamole for ssh sessions
  yum:
    name: dejavu-sans-mono-fonts
    state: present
  become: true

