---
- name: Ensuring Guacamole Server Service Is Enabled And Starts On Boot
  service:
    name: guacd
    enabled: true
    state: started
  become: true

- name: Ensuring Tomcat Is Enabled And Starts On Boot
  service:
    name: "{{ guacamole_tomcat_service }}"
    enabled: true
    state: started
  become: true
